version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_DATABASE=codingcollective_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=codingcollective_db
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 3500:80
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    ports:
      - 9000:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app